export const challenges = [
  "Trade items with a stranger",
  "Dance in public",
  "Try a new food",
  "Bake something new",
  "Walk to a park",
  "Make a new friend",
  "Sing in public",
  "Host a hangout",
  "Teach someone a new skill",
  "Learn a new language",
  "Do a random act of kindness",
  "Draw your friend with your eyes closed",
  "Blow bubbles",
  "Make a cool outfit",
  "Have a movie night",
  "Write a card for a loved one",
  "Make a fake flyer and hand it out",
  "Set up a mystery box exchange",
  "Host a themed snack party",
  "Get wrapped in bubble wrap",
  "Make a DIY",
  "Run somewhere new",
  "Try an unusual food combination",
  "Do a karaoke night",
  "Drive to a random nearby town",
  "Bake cookies in fun shapes",
  "Photoshop your friends into funny situations",
  "Have a sunset picnic",
  "Make art out of trash",
  "Do 2-person yoga",
];
